### ISSUE TITLE
Kramdown::Error: kramdown has no parser to handle the specified input format: GFM

### ISSUE THREAD

**Issue by zedtux** [coreyti/beckett#1]
Trying to import my Markdown content as the following:

```ruby
changelog = File.read('CHANGELOG.md')
hash = Beckett::Document.new(changelog).to_hash
```

fails:

```
rails aborted!
Kramdown::Error: kramdown has no parser to handle the specified input format: GFM
/usr/local/bundle/gems/kramdown-2.3.0/lib/kramdown/document.rb:104:in `initialize'
/usr/local/bundle/gems/beckett-0.1.0/lib/beckett.rb:26:in `new'
/usr/local/bundle/gems/beckett-0.1.0/lib/beckett.rb:26:in `to_hash'
/application/lib/tasks/versions.rake:11:in `block (2 levels) in <main>'
/usr/local/bundle/gems/railties-6.0.3.3/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/usr/local/bundle/gems/railties-6.0.3.3/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/usr/local/bundle/gems/railties-6.0.3.3/lib/rails/command.rb:48:in `invoke'
/usr/local/bundle/gems/railties-6.0.3.3/lib/rails/commands.rb:18:in `<main>'
/usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/usr/local/bundle/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `block in require'
/usr/local/bundle/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:291:in `load_dependency'
/usr/local/bundle/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => versions:notify_new_version
(See full trace by running task with --trace)
```

**Comment by zedtux** [comment]
And `beckett help` doesn't work for me:

```
bundler: command not found: beckett
Install missing gem executables with `bundle install`
```
